### PR TITLE
Zoom scale fix

### LINKED ISSUE #20: Zoom scale issue
The zoom scale factor set in the geocode plugin settings is not correctly handled when the geocoder call is preceded by a resize of QGis window

### PR DESCRIPTION
**Pull request by davtorgh**
Closes #20 by fixing an issue in handling the correct zoom scale factor in successive geocoder calls when resizing QGis window. This commit contains the following changes to GeoCoding.py:

 * removed scale_factor constant;
 * added call to canvas.zoomScale() method to set the correct zoom scale on every geocoder call.

Tested with QGis 2.8.7. Everything seems to work fine.

@elpaso, can you please merge the changes and update qgis-geocoding in the QGis plugin repository?

### CODE REVIEW

**Comment by davtorgh** [comment]
Hi @elpaso, is there any problem with this merge? Is is still pending...

**Comment by elpaso** [comment]
Sorry, lack of time and I forgot it. I've just committed a few modifications on the zoom logic. Please have a look if that fixes your issue.
See:
https://github.com/elpaso/qgis-geocoding/commit/1c25be6ea986f633dacee81ff573055be96f9fab#diff-39680a31827b8eedd5da83ec1a5a270bL305

**Comment by davtorgh** [comment]
Ok @elpaso, it works fine! I'm going to close #20 and the pull request.
Please, remember to load the new version of qgis-geocoding to the QGis plugin repository.

By the way, i think #2 and #6 can be closed.

Thank you.

**Comment by davtorgh** [comment]
Just a question @elpaso. Why did you set, in the metadata, QGis 2.14 as the lowest version compatible with the plugin?
I'm using QGis 2.8 LTS and I had to modify the metadata information in my local file to make it work, and seems to work well.

Thank you

**Pull request closed without merging**
